version: '3.5'


networks:
  default:
  inception-net:
    name: inception-net

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception-net
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file: .env
    restart: on-failure


  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception-net
    volumes:
      - wordpress_v:/var/www/html
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception-net
    volumes:
      - wordpress_v:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure


volumes:
  mariadb_v:
    driver: local
    driver_opts:
      device: /home/anahi/data/mariadb
      type: none
      o: bind

  wordpress_v:
    driver: local
    driver_opts:
      device: /home/anahi/data/wordpress
      type: none
      o: bind