version: '3.5'

networks:
  default:
  inception-net:
    name: inception-net

services:
  mariadb:
    container_name: mariadb-container
    image: mariadb-image
    build: 
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_dir:/var/lib/mysql/
    networks:
      - inception-net
    env_file: .env
    restart: unless-stopped


  wordpress:
    container_name: wordpress-container
    image: wordpress-image
    build: ./requirements/wordpress
    volumes:
      - wordpress_dir:/var/www/wordpress
    networks:
      - inception-net
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx-container
    image: nginx-image
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_dir:/var/www/wordpress
    networks:
      - inception-net
    depends_on:
      - wordpress
    restart: unless-stopped

volumes:
  mariadb_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/anahi/data/mariadb

  wordpress_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/anahi/data/wordpress

