version: '3.5'

networks:
  default:
  inception-net:
    name: inception-net

services:
  mariadb:
    container_name: mariadb
    image: inception-mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_dir:/var/lib/mysql/
    networks:
      - inception-net
    env_file: .env
    restart: unless-stopped


  wordpress:
    container_name: wordpress
    image: inception-wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_dir:/var/www/wordpress
    networks:
      - inception-net
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: inception-nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_dir:/var/www/wordpress
    networks:
      - inception-net
    depends_on:
      - wordpress
    restart: unless-stopped

volumes:
  mariadb_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/anahi/data/mariadb

  wordpress_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/anahi/data/wordpress

