version: '3.5'

networks:
  default:
  inception-net:
    name: inception-net

volumes:
  wordpress_dir:
    name: wordpress_dir
    driver: local
    driver_opts:
      device: /home/anahi/data/wordpress
      o: bind
      type: none

  mariadb_dir:
    name: mariadb_dir
    driver: local
    driver_opts:
      device: /home/anahi/data/mariadb
      o: bind
      type: none


services:
  mariadb:
    image: inception-mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_dir:/var/lib/mysql
    networks:
      - inception-net
    env_file: .env
    restart: on-failure


  wordpress:
    image: inception-wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_dir:/var/www/html
    networks:
      - inception-net
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    image: inception-nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_dir:/var/www/html
    networks:
      - inception-net
    depends_on:
      - wordpress
    restart: on-failure
