#!/bin/bash

service mysql start

mysql -u root -e "CREATE DATABASE ${DB_NAME};"
mysql -u root -e "CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';"
mysql -u root -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';"
mysql -u root -e "FLUSH PRIVILEGES;"
mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT_PASSWORD}';"





FROM debian:buster

#this exposes the port only to the other docker containers, but not to host
EXPOSE 3306

ARG DB_NAME=${DB_NAME}
ARG DB_USER=${DB_USER}
ARG DB_PASSWORD=${DB_PASSWORD}
ARG DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

RUN apt-get update && apt-get install \
	mariadb-server -y && \
	rm -rf /var/lib/apt/lists/*

RUN rm /etc/mysql/mariadb.conf.d/50-server.cnf
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d

COPY tools/create_user.sh /
RUN bash ./create_user.sh

# RUN service mysql start && \
# 	mysql < create_db_user.sql && \
RUN rm -rf create_user.sh

CMD ["mysqld_safe"]

# test if you can connect to maridb database
# sudo docker exec -it mariadb mariadb --user arendon_ -proot
# SHOW DATABASES;
# USE wordpress;
# SHOW TABLES


version: '3.5'


networks:
  inception: {}

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file: .env
    restart: unless-stopped


  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped


volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/arendon_/data/mariadb

  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/arendon_/data/wordpress